### ISSUE TITLE
Wrong TF between MAP and Odom

### ISSUE THREAD

**Issue by abylikhsanov** [appliedAI-Initiative/orb_slam_2_ros#13] opened 2019-03-01 14:00 UTC
From my understanding, Node.cc provides a TF between camera and Map. I have changed camera to odom in order to not break my tree but seems that the transformation is wrong. This is the screenshot:

![screen shot 2019-03-01 at 14 48 42](https://user-images.githubusercontent.com/13608445/53642744-b6896600-3c32-11e9-8793-648f67edcc4d.png)

As you can see, the rotation is being changed in yaw and roll. 
I do not want to use the position approximation by openCV but I would like it to fuse it together with my odometry. 

Can you tell me if that suppose to happen?

Also, when I switch to odom or base_link fixed frame, I get the pointcloud above my camera:

![screen shot 2019-03-01 at 15 03 11](https://user-images.githubusercontent.com/13608445/53642984-416a6080-3c33-11e9-99b7-c718785db32c.png)

**Comment by lennarthaller** [comment] 2019-03-01 14:41
Hey, 
thank you for reporting this.

> From my understanding, Node.cc provides a TF between camera and Ma
This is correct, that is the expected behavior. 

> As you can see, the rotation is being changed in yaw and roll.
Very strange indeed.

> Can you tell me if that suppose to happen?
This is not supposed to happen. I have never checked against the odom frame. I am going to look into this at some point (maybe in a week or two) but am very busy right now with other things.

If you want to implement a fix I'd be happy to get a pull request.

**Comment by saoto28** [comment] 2019-03-08 03:10
Hi, I have similar issue.
In my case, I just run the original launch files with realsense D435.
$ roslaunch realsense2_camera rs_rgbd.launch
$ roslaunch orb_slam2_ros orb_slam2_d435_rgbd.launch

This is the screenshot in which the camera_link is fixed frame. I can see the point cloud of the map above the camera as same as abylikhsanov's.
![screenshot from 2019-03-08 11-44-08](https://user-images.githubusercontent.com/33110199/54004950-edafc800-419a-11e9-9c95-bf8fb1177464.png)
Let me know if you have any suggestion.

**Comment by lennarthaller** [comment] 2019-03-08 11:09
Also just in the Odom frame?
This needs to be fixed but I cant say at the moment when I get around to do it.
The transformations are calculated in the file ros/src/Node.cc if it's a pressing issue for now and you feel comfortable you can try to fix it.

**Comment by lennarthaller** [comment] 2019-03-12 16:40
![Screenshot from 2019-03-12 15-40-23](https://user-images.githubusercontent.com/435012/54218332-a9e7f600-44ed-11e9-8cce-55c82abf5183.jpg)
Here is a screenshot of my tf tree which doesnt have odom. Can you show me how your tf tree looks like?
![Screenshot from 2019-03-12 15-45-18](https://user-images.githubusercontent.com/435012/54218333-a9e7f600-44ed-11e9-8033-0462666b8777.jpg)
This is how the point cloud looks with this tf.

**Comment by saoto28** [comment] 2019-03-13 07:05
Thank you for the response.
In my case, no Odom frame is created, the tree is no problem, and the point cloud of map is created.
The only problem is just tf between map and camera_link. 
It may be different issue from abylikhsanov's.
I will make new topic for my issue.

**Comment by lennarthaller** [comment] 2019-03-18 09:56
Let me know if #15 which I just merged fixed your issue.

**Comment by lennarthaller** [comment] 2019-04-21 08:13
Closing this due to inactivity. Feel free to reopen if needed.

**Closed by lennarthaller** 2019-04-21 08:13 UTC
